version: '3'
services:
  
  mongodb:
    restart: always
    image: mongo:5.0
    #image: erangaeb/senzmongodb:0.1
    
    ports:
      - "27017:27017" 
    volumes:
      - './database:/data/db'


  

  serveur:
    restart: always
    build:
      context: ./api
      
    command: sh -c "cd /usr/src/app/ && chmod +x init.sh && ./init.sh"
    ports:
      - 80:8000
    depends_on: 
      - mongodb
    volumes: 
      - ./api:/usr/src/app

    
